name: workify
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.7.2
  google_maps_flutter: ^2.10.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  table_calendar: ^3.1.3
  toastification: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand_Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand_Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand_Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand_Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
# flutter_assets:
#   assets_path: assets/images/
#   output_path: lib/core/constants/
#   filename: app_images.dart
flutter_native_splash:
  color: "#28333F"
  image: assets/images/logo_normal.png
  android_12:
    image: assets/images/native_splash_logo.png

  web: false
