// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd5DBTcg9dLeO8TAdBbZQIeg3mhccAccQ',
    appId: '1:1042958209407:web:317375b5114afc9796ca4a',
    messagingSenderId: '1042958209407',
    projectId: 'workify-b1e27',
    authDomain: 'workify-b1e27.firebaseapp.com',
    storageBucket: 'workify-b1e27.firebasestorage.app',
    measurementId: 'G-7XFMRPKNFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA24cvYTyEDxH655RmJi-LX1PZGRPtEwy4',
    appId: '1:1042958209407:android:2c60300bc86e0abd96ca4a',
    messagingSenderId: '1042958209407',
    projectId: 'workify-b1e27',
    storageBucket: 'workify-b1e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKOMiYvm5bmyIPNc1aehixGQbGc3_GmU',
    appId: '1:1042958209407:ios:d5a5bfc2ff069e6896ca4a',
    messagingSenderId: '1042958209407',
    projectId: 'workify-b1e27',
    storageBucket: 'workify-b1e27.firebasestorage.app',
    iosBundleId: 'com.example.workify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKOMiYvm5bmyIPNc1aehixGQbGc3_GmU',
    appId: '1:1042958209407:ios:d5a5bfc2ff069e6896ca4a',
    messagingSenderId: '1042958209407',
    projectId: 'workify-b1e27',
    storageBucket: 'workify-b1e27.firebasestorage.app',
    iosBundleId: 'com.example.workify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd5DBTcg9dLeO8TAdBbZQIeg3mhccAccQ',
    appId: '1:1042958209407:web:8ee0303c302c6b4f96ca4a',
    messagingSenderId: '1042958209407',
    projectId: 'workify-b1e27',
    authDomain: 'workify-b1e27.firebaseapp.com',
    storageBucket: 'workify-b1e27.firebasestorage.app',
    measurementId: 'G-H2ZE44D3D5',
  );
}
